# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98e5282ecdfa402cb9d7758dabd3e41e9751da677c6e9ed6fc1a27203a07c81400ed191d59d04910bc5e4e7ad9d0542664b7cd188c3e74501e817ee0b8044571

test:
  secret_key_base: c601b67f0475bb36ed1ffef9cbc8a7b2da7900c306774fe636af74073886b7c04ddcb30ef2039c204c73da46970fa0fd7e8c48a20088a947a0e9161750167a1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
